### ISSUE TITLE
你好，行车证在哪里找到的训练集，能提供下吗？

### ISSUE THREAD

**Issue by WhiteAzzan** [YIYIMZ/my_orc_keras_verification_code_identification#1]
谢谢，提供下数据集吧

**Comment by YIYIMZ** [comment]
麻烦把源码的文件都略看看呀，文件名也语意比较好，数据集就在源码里，不要这样拿来主意。

**Comment by YIYIMZ** [comment]
> 谢谢，提供下数据集吧

麻烦把源码的文件都略看看呀，文件名也语意比较好，数据集就在源码里，不要这样拿来主意。

**Comment by WhiteAzzan** [comment]
好的

**Comment by xinyuegtxy** [comment]
哪里啊，我特么看不见啊，源码里哪里有数据啊？？这个人写的代码都不写readme吗

**Comment by WhiteAzzan** [comment]
已经解决行驶证问题 可以用代码生成

**Comment by YIYIMZ** [comment]
@xinyuegtxy 看最新readme文件，WhiteAzzan同学已经发现了。
